name: Run Login Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */3 * *"  # 每三天运行一次
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest

    env:  # 统一定义环境变量，避免重复
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v3  # 使用具体的版本

      - name: 设置 Python 环境
        uses: actions/setup-python@v4  # 使用最新的具体版本
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}  # 缓存依赖，加速运行
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create accounts.json from environment variable
        run: echo "$ACCOUNTS_JSON" > accounts.json

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pyppeteer aiofiles requests  # 合并 pip install 命令，提升效率

      - name: 运行登录脚本
        run: |
          python login_script.py
